### ISSUE TITLE
Runner breaks when the submitted solution has an undefined variables

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-gobstones-runner#73]
See the following code: 

```gobstones
function hayEscuelaPublica() {
  if (colorEstudiantes > 0) {
    EntregarLoQueAlcance()
  }
  return (ReportarSituacion())
}
```

It will produce 

```
/usr/local/bundle/gems/mumuki-gobstones-runner-1.5.0/lib/render/html_board.rb:8:in `initialize'
/usr/local/bundle/gems/mumuki-gobstones-runner-1.5.0/lib/render/html_renderer.rb:79:in `new'
/usr/local/bundle/gems/mumuki-gobstones-runner-1.5.0/lib/render/html_renderer.rb:79:in `visible_board'
/usr/local/bundle/gems/mumuki-gobstones-runner-1.5.0/lib/render/html_renderer.rb:62:in `block in prepare_boards'
/usr/local/bundle/gems/mumuki-gobstones-runner-1.5.0/lib/render/html_renderer.rb:60:in `map'
/usr/local/bundle/gems/mumuki-gobstones-runner-1.5.0/lib/render/html_renderer.rb:60:in `prepare_boards'
/usr/local/bundle/gems/mumuki-gobstones-runner-1.5.0/lib/render/html_renderer.rb:24:in `render_error_check_failed_unexpected_boom'
/usr/local/bundle/gems/mumuki-gobstones-runner-1.5.0/lib/render/with_renderer.rb:13:in `render_error_output'
/usr/local/bundle/gems/mumukit-2.20.0/lib/mumukit/metatest/checker.rb:7:in `rescue in check'
/usr/local/bundle/gems/mumukit-2.20.0/lib/mumukit/metatest/checker.rb:3:in `check'
/usr/local/bundle/gems/mumukit-2.20.0/lib/mumukit/metatest/framework.rb:17:in `example'
/usr/local/bundle/gems/mumukit-2.20.0/lib/mumukit/metatest/framework.rb:9:in `block in test'
/usr/local/bundle/gems/mumukit-2.20.0/lib/mumukit/metatest/framework.rb:9:in `map'
/usr/local/bundle/gems/mumukit-2.20.0/lib/mumukit/metatest/framework.rb:9:in `test'
/usr/local/bundle/gems/mumuki-gobstones-runner-1.5.0/lib/gobstones/batch.rb:12:in `run_tests!'
/usr/local/bundle/gems/mumuki-gobstones-runner-1.5.0/lib/test_hook.rb:6:in `run!'
/usr/local/bundle/gems/mumukit-2.20.0/lib/mumukit/server/test_server.rb:88:in `compile_and_run'
/usr/local/bundle/gems/mumukit-2.20.0/lib/mumukit/server/test_server.rb:63:in `run_tests!'
/var/www/runner/lib/prefer_static_analysis.rb:7:in `evaluate!'
/usr/local/bundle/gems/mumukit-2.20.0/lib/mumukit/server/test_server.rb:36:in `block in test!'
/usr/local/bundle/gems/mumukit-2.20.0/lib/mumukit/server/test_server.rb:102:in `respond_to'
/usr/local/bundle/gems/mumukit-2.20.0/lib/mumukit/server/test_server.rb:34:in `test!'
/usr/local/bundle/gems/mumukit-2.20.0/lib/mumukit/server/app.rb:51:in `block in '
/usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
/usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
/usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
/usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
/usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
/usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
/usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
/usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
/usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
/usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
/usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
/usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
/usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
/usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
/usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
/usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
/usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
/usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
/usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
/usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
/usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
/usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
/usr/local/bundle/gems/rack-protection-1.5.4/lib/rack/protection/xss_header.rb:18:in `call'
/usr/local/bundle/gems/rack-protection-1.5.4/lib/rack/protection/path_traversal.rb:16:in `call'
/usr/local/bundle/gems/rack-protection-1.5.4/lib/rack/protection/json_csrf.rb:18:in `call'
/usr/local/bundle/gems/rack-protection-1.5.4/lib/rack/protection/base.rb:49:in `call'
/usr/local/bundle/gems/rack-protection-1.5.4/lib/rack/protection/base.rb:49:in `call'
/usr/local/bundle/gems/rack-protection-1.5.4/lib/rack/protection/frame_options.rb:31:in `call'
/usr/local/bundle/gems/rack-1.6.9/lib/rack/logger.rb:15:in `call'
/usr/local/bundle/gems/rack-1.6.9/lib/rack/commonlogger.rb:33:in `call'
/usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:219:in `call'
/usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:212:in `call'
/usr/local/bundle/gems/rack-1.6.9/lib/rack/head.rb:13:in `call'
/usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:25:in `call'
/usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
/usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
/usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
/usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
/usr/local/bundle/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
/usr/local/bundle/gems/puma-3.11.2/lib/puma/configuration.rb:225:in `call'
/usr/local/bundle/gems/puma-3.11.2/lib/puma/server.rb:624:in `handle_request'
/usr/local/bundle/gems/puma-3.11.2/lib/puma/server.rb:438:in `process_client'
/usr/local/bundle/gems/puma-3.11.2/lib/puma/server.rb:302:in `block in run'
/usr/local/bundle/gems/puma-3.11.2/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

on exercise https://mumuki.io/exercises/2347-fundamentos-practica-igualmente-conectados-escuelas-publicas-y-privadas

**Comment by rodri042** [comment]
Hmm, looks very similar to https://github.com/mumuki/mumuki-gobstones-runner/issues/64

Was that fix deployed to production?

**Comment by flbulgarelli** [comment]
Duplicated of #64.
